version: 2

sources:
  - name: customer_schema
    schema: dbt_demo_geographic_customer
    tables:
      - name: CUSTOMER_ADDRESSES
  - name: orders_schema
    schema: dbt_demo_geographic_orders
    tables:
      - name: ORDERS
